# Generated by Django 3.1.4 on 2021-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20201224_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.CharField(default='https://picsum.photos/300/200', max_length=300),
        ),
    ]
